apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-node-status-readonly
  labels:
    {{- include "kube-node-status.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kube-node-status.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: kube-node-status-readonly
  apiGroup: rbac.authorization.k8s.io
