apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-node-status.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "kube-node-status.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 2112
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "kube-node-status.selectorLabels" . | nindent 4 }}
